import BackButton from "../components/BackButton"

export default function Growth(){
   return (
       <>
       <div className="backbtn-blog-container">
           <BackButton className="backbtn-blog" path="/blog"/>
       </div>
       <div className="blog-post-container fade-in">
           <h2 className="blog-post-title">Graduation, App, and Growth</h2>
           <h3 className="blog-post-date">May 9, 2026</h3>
           <hr/>
           <p>I’ve officially graduated with a computer science degree from Laurier, and that means I'm entering a new chapter of my life. No more structure that comes with being in school. Reflecting on the past four years, I’d say there've been a lot of good decisions I’ve made and also a lot of decisions I didn’t make that could’ve put me in a better position career wise. However, I’m trying to dwell less on the past and be more present and forward facing so I’m going to talk about where I’m at right now and my current aspirations.

In March, I launched meet a hawk on the iOS app store. This was an idea that was marinating in my head for over a year (last summer specifically) when I was learning frontend development. I built my first iteration on January 19, 2026 and the app was approved on March 8, 2026. So, it took around 48 days from idea to production. This was an app that I was intrinsically motivated to make for multiple reasons. Firstly, I knew how difficult it can be to actually make friends and meet new people in a university environment. In my own experience, students in my program never really attended class. Weird class schedules can make it difficult to attend social events hosted by clubs. Going up to people or messaging random people that go to your school can be pretty awkward too. I personally invested time into becoming executives of clubs to bridge those gaps. Those were my initial feelings and they were validated when I scrolled through Reddit. I’d see a post by students saying how difficult it was to make friends and how people already formed friend groups. I felt their pain and I got to work. <br/><br/>My idea was simple: make an app specifically for Laurier students that reduced the friction between meeting new people, make it easier to find people with similar interests, an app that wasn’t a dating platform, and didn’t involve infinite scrolling. I chose to make an app instead of a website because making mobile apps on a browser feels very janky. I chose iOS because I personally use an iPhone (android port coming soon). However, my biggest problem was that I’ve never touched XCode, Swift, or knew anything about mobile development and so now I wanna discuss some of the problems I ran into and some of the things I learned.

Making an iOS app even with the wonders of AI was not easy. Without my CS background, this project would’ve taken a lot longer to figure out. My first problem was with responsive design. I’d launch the app on the simulator and it’d look perfect. Then I’d create a test build and download it on my phone and it’d look terrible. This was despite avoiding fixed sizes and using adaptive layouts. My solution to this problem was simply trial and error. The second roadblock was the app store review process. Putting a lot of energy into an app that you’re overconfident (and blissfully ignorant about) then getting the rejection notification was disheartening, on par with getting rejected by a girl. App store reviewers look at thousands of apps per day and frankly don’t have the time to write a detailed description on why the app didn’t meet their standards. My app was rejected seven times before being approved. The first being that I didn’t implement reporting or blocking. <br/><br/>The many being minimum functionality requirements. If the reviewer feels like the app isn’t good enough they can reject it. This is a subjective process as the app store is a curated list, not a checkbox or list of requirements. Something I regret not doing earlier was taking advantage of the virtual appointments that Apple offers where you can talk to a member of the review team to discuss your app. I forget his name, but he was one of the head reviewers from California and was an amazing guy to talk to. He believed my app was close to approval and I just needed one more thing to push it past the finish line. That’s where we brainstormed and bounced back ideas. I was hesitant to add more features with the possibility that it would still result in the app being disapproved. I told him my idea about the pinboard, where students can post things that relate to the three categories being academic/social/club related, and he said that was the best idea after we brainstormed with each other. It was interesting talking to him about how apps have really evolved over the past ten years with newer technologies like crypto, sports betting, and now AI. The amount of app store submissions have increased exponentially since then. <br/><br/> Anyways, I developed the pinboard and the app got approved. The app has been downloaded 130+ times which is good considering the time of launch being towards exam season. This is something that I just wanted to get out there with the hopes of it providing value to somebody and clearly there’s been demand for it. I recently saw a post on Reddit where someone recommended my app to a person who was looking to meet new people. If I’ve helped one person make a new friend, that has achieved my goal and I’m incredibly grateful I put the time into developing this application. From my friend Lucas telling me my app completely sucks (on the first iteration) to this in 48 days is amazing.<br/><br/>

Where I’m at now. As of the time I’m writing this it’s May 9th, 2026. Being graduated and now working as a remote web developer for the next couple of months. I have a ton of leverage, which is my time. Being in the prime age of learning things quickly I’ve been devoting my time to just that, learning. In contrast to school where you’re managing five courses at once and deadlines, being able to sit down and focus on one thing is nice. I’m in the process of learning backend development on boot.dev and will likely be finishing the pathway within the next month. I read Apprenticeship Patterns recently and the book helped me see software from a different perspective that align with my view of software engineering. The more I learn about software, the more tools and concepts are at my disposal, and this ultimately leads me to have the ability to solve larger and larger problems. The fact that I made an app used by a hundred students with my current knowledge of development gives me the confidence that I can make a positive impact on maybe a thousand, a hundred-thousand, or even a million people in the future. This is enough reason for me to keep on developing my craft and continue to learn new concepts. <br/><br/>Fundamentally, being creative is having expertise on multiple subjects so you can combine them to make something unique. If another idea somehow comes to me, I want to be technically ready to execute the idea at a rapid pace and be able to scale the software. There’s a seemingly never ending amount of books I want to read, bloggers I want to keep up to date with, and technologies I want to add to my toolbox. Programming aside, I also want to relearn mathematics from ground zero. Being able to read and interpret the newest papers on machine learning and topics like finance/economics require a good intuition for math. I’m not sure how long this is going to take but I feel like it will pay off. In addition to mathematics, I’ve been reading a textbook on Microeconomics and exploring literature. I really want to develop a broader and better understanding of the world by learning the fundamentals of most of the disciplines. For example, history, chemistry, physics, sociology, political science, anthropology, etc. I’m curious to see how my learning over the next eight years (when I’m 30) will compound. I recently read a philosophy textbook and that really opened my eyes on how wildly differently people have lived their lives over the past thousands of years. I really do think it’s necessary to constantly question the world and question my own beliefs and behaviours.<br/><br/>
With that being said, I feel like I’ve yapped a lot. Career wise, I’m not really aiming for a specific company or anything along that matter. I’m going to continue investing in myself, taking calculated risks, getting out of my comfort zone, and actively developing my relationships. 
</p>
       </div>
       </>
   )
}
